from typing import Dict, Any
from db import Database
from github_client import GitHubClient
from config import Config

class CoordinatorAgent:
    """Compiles final review from all agent outputs and posts to PR"""
    
    def __init__(self):
        self.db = Database()
        self.github_client = GitHubClient()
    
    def run(self, pr_number: int) -> Dict[str, Any]:
        """Compile and post final review"""
        print(f"Running Coordinator Agent for PR #{pr_number}")
        
        # Get all agent outputs
        all_outputs = self.db.get_all_agent_outputs(pr_number)
        
        # Compile final review
        final_review = self._compile_final_review(all_outputs)
        
        # Post to GitHub
        try:
            self.github_client.create_comment(pr_number, final_review)
            post_success = True
        except Exception as e:
            print(f"Failed to post comment: {e}")
            post_success = False
        
        result = {
            'final_review_generated': True,
            'review_posted': post_success,
            'agents_processed': len(all_outputs),
            'review_length': len(final_review)
        }
        
        # Save to database
        self.db.save_agent_output(pr_number, 'coordinator_agent', result)
        
        return result
    
    def _compile_final_review(self, all_outputs: Dict[str, Any]) -> str:
        """Compile final review from all agent outputs"""
        review_parts = []
        
        review_parts.append("# 🤖 Multi-Agent PR Review Report")
        review_parts.append("")
        
        # Early Policy Findings
        if 'early_policy_agent' in all_outputs:
            early_data = all_outputs['early_policy_agent']
            review_parts.append("## 📋 Early Policy Check")
            if early_data.get('issues_found'):
                review_parts.append("❌ **Issues Found:**")
                for issue in early_data['issues_found']:
                    review_parts.append(f"- {issue}")
            if early_data.get('warnings'):
                review_parts.append("⚠️ **Warnings:**")
                for warning in early_data['warnings']:
                    review_parts.append(f"- {warning}")
            review_parts.append("")
        
        # Summary
        if 'summarizer_agent' in all_outputs:
            summary_data = all_outputs['summarizer_agent']
            if summary_data.get('generation_success'):
                review_parts.append("## 📝 PR Summary")
                review_parts.append(summary_data['summary'])
                review_parts.append("")
        
        # Code Review
        if 'reviewer_agent' in all_outputs:
            review_data = all_outputs['reviewer_agent']
            if review_data.get('review_success'):
                review_parts.append("## 🔍 Code Review Findings")
                review_parts.append(review_data['review_findings'])
                review_parts.append("")
        
        # Policy Violations
        if 'deep_policy_agent' in all_outputs:
            policy_data = all_outputs['deep_policy_agent']
            if policy_data.get('policy_violations'):
                review_parts.append("## ⚠️ Policy Violations")
                for violation in policy_data['policy_violations']:
                    review_parts.append(f"- {violation}")
                review_parts.append("")
        
        # Questions
        if 'ask_agent' in all_outputs:
            ask_data = all_outputs['ask_agent']
            if ask_data.get('clarifying_questions'):
                review_parts.append("## ❓ Clarifying Questions")
                for question in ask_data['clarifying_questions']:
                    review_parts.append(f"- {question}")
                review_parts.append("")
        
        review_parts.append("---")
        review_parts.append("*This review was automatically generated by the Multi-Agent PR Review Orchestrator*")
        
        return "\n".join(review_parts)